
version: "3.8"

services:
        nginx:
                   image: nginx:latest
                   container_name: aplicacao
                   ports:
                            - "8080:8080"
                   volumes:
                            - ./site:/site
                            - ./nginx.conf:/etc/nginx/conf.d/default.conf
                
                   networks:
                            - site-network
networks:
        site-network:
                driver: bridge
